var config = {
    OWM_KEY : 'OPEN-WEATHER-MAP-KEY-HERE',
    GCAL_ID : 'GOOGLE-CALENDAR-ID-HERE',
    GCAL_API_KEY : 'GOOGLE-CALENDAR-API-KEY-HERE',
    SpotClientID : 'SPOTIFY-CLIENT-ID-HERE',
    COINMARKET_CAP_KEY : 'COINMARKET-CAP-KEY-HERE',
}